apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-tagger
  namespace: media-tagger
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: media-tagger.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: media-tagger
                port:
                  number: 3000
  tls:
    - hosts:
        - media-tagger.example.com
      secretName: media-tagger-tls
